GET http://localhost:3001/api/orders

###

POST http://localhost:3001/api/orders
Content-Type: application/json

{
  "resumeProducts": [{
    "item": "Galaxy A20",
    "quantity": 2
  },
  {
   "item": "Galaxy A20",
    "quantity": 2
  }],
  "total": 3500
}

###

DELETE http://localhost:3001/api/orders/638686d520d52d6c2349fa67